<?php

return [
    [
        'key' => 'sales.wallet',
        'name' => 'wallet::app.admin.configuration.index.wallet.title',
        'info' => 'wallet::app.admin.configuration.index.wallet.info',
        'icon' => 'settings/payment-method.svg',
        'sort' => 11,
    ],
    [
        'key' => 'sales.wallet.settings',
        'name' => 'wallet::app.admin.configuration.index.wallet.title',
        'info' => 'wallet::app.admin.configuration.index.wallet.info',
        'icon' => 'settings/payment-method.svg',
        'sort' => 1,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'wallet::app.admin.configuration.index.wallet.active',
                'type' => 'boolean',
                'default' => true,
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'enable_topup',
                'title' => 'wallet::app.admin.configuration.index.wallet.enable-topup',
                'type' => 'boolean',
                'default' => true,
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'enable_withdrawal',
                'title' => 'wallet::app.admin.configuration.index.wallet.enable-withdrawal',
                'type' => 'boolean',
                'default' => true,
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'min_topup_amount',
                'title' => 'wallet::app.admin.configuration.index.wallet.min-topup-amount',
                'type' => 'text',
                'default' => '10.00',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'min_withdrawal_amount',
                'title' => 'wallet::app.admin.configuration.index.wallet.min-withdrawal-amount',
                'type' => 'text',
                'default' => '50.00',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'max_withdrawal_amount',
                'title' => 'wallet::app.admin.configuration.index.wallet.max-withdrawal-amount',
                'type' => 'text',
                'default' => '0',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'withdrawal_methods',
                'title' => 'wallet::app.admin.configuration.index.wallet.withdrawal-methods',
                'type' => 'blade',
                'path' => 'wallet::admin.configuration.withdrawal-methods',
            ],
        ],
    ],
    [
        'key' => 'sales.payment_methods.wallet',
        'name' => 'wallet::app.admin.system.payment-methods.wallet-title',
        'info' => 'wallet::app.admin.system.payment-methods.wallet-info',
        'sort' => 1,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'wallet::app.admin.system.payment-methods.status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'title',
                'title' => 'wallet::app.admin.system.payment-methods.method-title',
                'type' => 'text',
                'depends' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'wallet::app.admin.system.payment-methods.description',
                'type' => 'textarea',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => true,
            ],
            [
                'name' => 'image',
                'title' => 'wallet::app.admin.system.payment-methods.logo',
                'type' => 'image',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => false,
                'validation' => 'mimes:bmp,jpeg,jpg,png,webp,svg',
            ],
            [
                'name' => 'sort',
                'title' => 'wallet::app.admin.system.payment-methods.sort-order',
                'type' => 'number',
                'depends' => 'active:1',
                'validation' => 'required_if:active,1|integer|min:0',
                'channel_based' => true,
                'locale_based' => false,
            ],
        ],
    ],
];
