<?php

return [
    [
        'key' => 'sales.wallet',
        'name' => 'wallet::app.admin.configuration.index.wallet.title',
        'info' => 'wallet::app.admin.configuration.index.wallet.info',
        'icon' => 'settings/payment-method.svg',
        'sort' => 11,
    ],
    [
        'key' => 'sales.wallet.settings',
        'name' => 'wallet::app.admin.configuration.index.wallet.title',
        'info' => 'wallet::app.admin.configuration.index.wallet.info',
        'icon' => 'settings/payment-method.svg',
        'sort' => 1,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'wallet::app.admin.configuration.index.wallet.active',
                'type' => 'boolean',
                'default' => true,
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'enable_topup',
                'title' => 'wallet::app.admin.configuration.index.wallet.enable-topup',
                'type' => 'boolean',
                'default' => true,
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'enable_withdrawal',
                'title' => 'wallet::app.admin.configuration.index.wallet.enable-withdrawal',
                'type' => 'boolean',
                'default' => true,
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'min_topup_amount',
                'title' => 'wallet::app.admin.configuration.index.wallet.min-topup-amount',
                'type' => 'text',
                'default' => '10.00',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'min_withdrawal_amount',
                'title' => 'wallet::app.admin.configuration.index.wallet.min-withdrawal-amount',
                'type' => 'text',
                'default' => '50.00',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'max_withdrawal_amount',
                'title' => 'wallet::app.admin.configuration.index.wallet.max-withdrawal-amount',
                'type' => 'text',
                'default' => '0',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'withdrawal_methods',
                'title' => 'wallet::app.admin.configuration.index.wallet.withdrawal-methods',
                'type' => 'blade',
                'path' => 'wallet::admin.configuration.withdrawal-methods',
            ],
        ],
    ],
    [
        'key' => 'sales.payment_methods.wallet',
        'name' => 'wallet::app.admin.system.payment-methods.wallet-title',
        'info' => 'wallet::app.admin.system.payment-methods.wallet-info',
        'sort' => 1,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'wallet::app.admin.system.payment-methods.status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'title',
                'title' => 'wallet::app.admin.system.payment-methods.method-title',
                'type' => 'text',
                'depends' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'wallet::app.admin.system.payment-methods.description',
                'type' => 'textarea',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => true,
            ],
            [
                'name' => 'image',
                'title' => 'wallet::app.admin.system.payment-methods.logo',
                'type' => 'image',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => false,
                'validation' => 'mimes:bmp,jpeg,jpg,png,webp,svg',
            ],
            [
                'name' => 'sort',
                'title' => 'wallet::app.admin.system.payment-methods.sort-order',
                'type' => 'number',
                'depends' => 'active:1',
                'validation' => 'required_if:active,1|integer|min:0',
                'channel_based' => true,
                'locale_based' => false,
            ],
        ],
    ],
    [
        'key' => 'sales.wallet_promotions',
        'name' => 'إعدادات العروض الترويجية للمحفظة (Wallet Promotions)',
        'info' => 'التحكم في أوضاع التشغيل، صندوق المعالجة الذري، ومطابقة الأرصدة',
        'icon' => 'settings/promotions.svg',
        'sort' => 12,
    ],
    [
        'key' => 'sales.wallet_promotions.settings',
        'name' => 'إعدادات التشغيل والـ Outbox',
        'info' => 'تحديد وضع التشغيل ومهلات المعالجة',
        'icon' => 'settings/promotions.svg',
        'sort' => 1,
        'fields' => [
            [
                'name' => 'mode',
                'title' => 'وضع التشغيل (Promotion Operating Mode)',
                'type' => 'select',
                'options' => [
                    [
                        'title' => 'الوضع القديم فقط (Legacy Only - Promotions Inactive)',
                        'value' => 'legacy_only',
                    ],
                    [
                        'title' => 'تفعيل العروض الترويجية (Promotions Active)',
                        'value' => 'promotions_active',
                    ],
                    [
                        'title' => 'الكتابة المزدوجة (Dual Write Mode)',
                        'value' => 'dual_write',
                    ],
                ],
                'default' => 'promotions_active',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'outbox_batch_size',
                'title' => 'حجم الدفعة المعالجة (Outbox Batch Size)',
                'type' => 'number',
                'default' => 50,
                'validation' => 'required|integer|min:1|max:500',
                'channel_based' => false,
                'locale_based' => false,
            ],
            [
                'name' => 'outbox_lease_seconds',
                'title' => 'مهلة القفل بالثواني (Outbox Lease Timeout Seconds)',
                'type' => 'number',
                'default' => 60,
                'validation' => 'required|integer|min:10|max:600',
                'channel_based' => false,
                'locale_based' => false,
            ],
        ],
    ],
];
